services:
  - docker

language: bash

script:
  - docker build -t pepov/alpine-tini .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push "pepov/alpine-tini"
    fi
