services:
  - docker

language: bash

script:
  - docker build -t pepov/alpine-tini .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pepov/alpine-tini
